# Generated by Django 3.2 on 2022-08-04 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedimages',
            name='file_name',
        ),
    ]
